<a href="https://colab.research.google.com/github/sairamsankranthi13-a11y/pandas-series/blob/main/pandas%20methods%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#pandas series methods
#head()
#tail()
#sum()
#count()
#mean()
#describe()
#unique()
#nunique()

print("HEAD")

import pandas as pd
n=[12,22,34,55,56,87,98,43,59]
s=pd.Series(n)
print(s)
print(s.head())

print()

#TAIL
print("tail")
import pandas as pd
n=[12,22,34,55,56,87,98,43,59]
s=pd.Series(n)
print(s)
print(s.head())

print()

#sum
print("sum")
import pandas as pd
n=[21,34,54,67,65,87]
s=pd.Series(n)
print(s)
print(s.sum())

print()

#count()
print()
import pandas as pd
n=[21,34,54,67,65,87]
s=pd.Series(n)
print(s)
print(s.count())

print()

#mean
import pandas as pd
n=[21,34,54,67,65,87]
s=pd.Series(n)
print(s)
print(s.mean())

print()

#describe
print("describe")
import pandas as pd
a= [21,34,54,67,65,87]
s=pd.Series(n)
print(s)
print(s.describe())

print()

#unique
print("unique")
import pandas as pd
n=[21,34,54,67,65,54,87,54,54,]
s=pd.Series(n)
print(s)
print(s.unique())

print()

#nunique
print("nunique")
import pandas as pd
n=[21,34,54,67,65,54,87,54,54,]
s=pd.Series(n)
print(s)
print(s.nunique())

HEAD
0    12
1    22
2    34
3    55
4    56
5    87
6    98
7    43
8    59
dtype: int64
0    12
1    22
2    34
3    55
4    56
dtype: int64

tail
0    12
1    22
2    34
3    55
4    56
5    87
6    98
7    43
8    59
dtype: int64
0    12
1    22
2    34
3    55
4    56
dtype: int64

sum
0    21
1    34
2    54
3    67
4    65
5    87
dtype: int64
328


0    21
1    34
2    54
3    67
4    65
5    87
dtype: int64
6

0    21
1    34
2    54
3    67
4    65
5    87
dtype: int64
54.666666666666664

describe
0    21
1    34
2    54
3    67
4    65
5    87
dtype: int64
count     6.000000
mean     54.666667
std      23.938811
min      21.000000
25%      39.000000
50%      59.500000
75%      66.500000
max      87.000000
dtype: float64

unique
0    21
1    34
2    54
3    67
4    65
5    54
6    87
7    54
8    54
dtype: int64
[21 34 54 67 65 87]